version: '3.4'

services:
  observerpattern:
    image: observerpattern:dev
    container_name: ObserverPattern
    build:
      args:
        source: obj/Docker/empty/
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ObserverPattern"
    volumes:
      - C:\Users\ariji\source\repos\ObserverPattern\ObserverPattern:C:\app
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "set DISABLE_PERFORMANCE_DEBUGGER=1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\bin\\Debug\\ObserverPattern.exe"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
